development:
  access_key: ENV['S3_ACCESS_KEY']
  secret_access_key: ENV['S3_SECRET_ACCESS_KEY']

test:
  access_key: ENV['S3_ACCESS_KEY']
  secret_access_key: ENV['S3_SECRET_ACCESS_KEY']

production:
  access_key: ENV['S3_ACCESS_KEY']
  secret_access_key: ENV['S3_SECRET_ACCESS_KEY']